# Generated by Django 4.0.3 on 2022-03-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(default='default.png', upload_to='seller/products/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand_name', models.ForeignKey(default='brand', on_delete=django.db.models.deletion.CASCADE, to='product.brand')),
            ],
        ),
    ]
