# Generated by Django 2.2.6 on 2022-07-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cms',
        ),
    ]
