# Generated by Django 2.2.6 on 2022-07-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_title_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='title',
            name='user',
        ),
    ]
