# Generated by Django 2.2.6 on 2022-07-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_auto_20220701_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='address',
            name='open_time',
        ),
        migrations.AddField(
            model_name='address',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='weekday',
            field=models.IntegerField(blank=True, choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], null=True, unique=True),
        ),
    ]
