# Generated by Django 4.0.3 on 2022-05-16 05:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('school_image', models.ImageField(upload_to='school_pics')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='school_video', verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(default='default.png', upload_to='admin/profile_img/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateTimeField(blank=True, default='', null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('b+', 'B+'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=5)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Buddish', 'Buddish'), ('Others', 'Others')], default='Hindu', max_length=15)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(default='default.png', upload_to='principal/profile_img/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('b+', 'B+'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=5)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Buddish', 'Buddish'), ('Others', 'Others')], default='Hindu', max_length=15)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
            options={
                'db_table': 'principal',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(default='default.png', upload_to='staff/profile_img/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('b+', 'B+'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='A+', max_length=5)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Buddish', 'Buddish'), ('Others', 'Others')], default='hindu', max_length=15)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='male', max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(default='default.png', upload_to='student/profile_img/')),
                ('fullName', models.CharField(default='', max_length=50)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('father_occupation', models.CharField(default='', max_length=100)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('b+', 'B+'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='A+', max_length=5)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Buddish', 'Buddish'), ('Others', 'Others')], default='hindu', max_length=15)),
                ('classe', models.CharField(choices=[('Play', 'Play'), ('Nursery', 'Nursery'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Tenth', 'Tenth'), ('Eleven', 'Eleven')], default='nursery', max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=20)),
                ('role', models.CharField(blank=True, max_length=12)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='male', max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.FileField(default='default.png', upload_to='teacher/profile_img/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('classe', models.CharField(choices=[('Play', 'Play'), ('Nursery', 'Nursery'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Tenth', 'Tenth'), ('Eleven', 'Eleven')], default='Nursery', max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], default='A', max_length=20)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('blood_group', models.CharField(choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('b+', 'B+'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], default='A+', max_length=5)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Buddish', 'Buddish'), ('Others', 'Others')], default='hindu', max_length=15)),
                ('mobile', models.CharField(default='', max_length=10)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='male', max_length=50)),
                ('address', models.TextField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('pincode', models.CharField(default='', max_length=6)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
