"""
Django settings for school project.

Generated by 'django-admin startproject' using Django 3.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from email.message import Message
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-7rtz8#h!!#ef+zp6^z^2%a8g5%gh1l^tlegq%x0()kz-fvoda^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

MESSAGE_STORAGE = "django.contrib.messages.storage.cookie.CookieStorage"
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'chat.apps.ChatConfig'
    'home',
    'student',
    'product',
    'order',
    'admin_portal',
    'crispy_forms',
    'social_django',
    'chatbot',
    'channels',
    'chat.apps.ChatConfig',
         
]




CHANNEL_LAYERS = {
    'default': {
        # "BACKEND": "channels.layers.InMemoryChannelLayer",
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        'CONFIG': {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}


CRISPY_TEMPLATE_PACK = 'bootstrap4'
MIDDLEWARE = [
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ## This middleware is used for user login with google account 
    'social_django.middleware.SocialAuthExceptionMiddleware',

   
]
SESSION_EXPIRE_SECONDS = 30
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True

ROOT_URLCONF = 'school.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',   
                'social_django.context_processors.login_redirect',
             

              
            ],
        },
    },
]

WSGI_APPLICATION = 'school.wsgi.application'

ASGI_APPLICATION = 'school.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'school_db',
    'USER': 'root',
    'PASSWORD': 'sms@123',
    'HOST': 'localhost',
    'PORT': '3306',
},

}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

################# This parts is used for cant login django admin pannel side

# AUTHENTICATION_BACKENDS = (
#     'django.contrib.auth.backends.RemoteUserBackend',
# )
################ end @#######################


STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)


MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')


LOGIN_REDIRECT_URL = 'student:student_profile'
LOGOUT_REDIRECT_URL = '/'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'home.User'  


## Stripe payment Integrations !!!!!!!!!!!!!!!!!!!!!##################################################

STRIPE_PUBLIC_KEY  = 'pk_test_51Kc2nkSA8HRMHYNa0tkcXDKVkg0cO6aWU8qiProc2tXLJoPnBZd1VZjVp6sALpGxrjcXhArn9GEDbLS7n83rx5pN004n26KDcB'
STRIPE_SECRET_KEY = 'sk_test_51Kc2nkSA8HRMHYNa7cjxMNqkgzSFL7mLZ9wEaGVoArtzLD9AS5pesjIxUsEK07DI93KX0oM4zxZxB9hRPlJLKq1600m4CyJYms'

## Paytm Integrations <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<############################################

# Payment configuration
PAYTM_MERCHANT_ID = 'POyPew32195302419864'
PAYTM_SECRET_KEY = 'gv_OgI5hgd6v3lUS'
PAYTM_WEBSITE = 'WEBSTAGING'
PAYTM_CHANNEL_ID = 'WEB'
PAYTM_INDUSTRY_TYPE_ID = 'Retail'


######## GOOGLE RECAPTCHA ###############
GOOGLE_RECAPTCHA_SECRET_KEY = '6LdwBYUfAAAAAEaq-UYQSumqsWpEKy0p5wA32tLp'
RECAPTCHA_PRIVATE_KEY = '6LdwBYUfAAAAAG7M5PkjrVmUG70bcZ6oBS6DJBxh'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.google.GoogleOAuth2',
     
)
########## GOOGLE  ######################
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '679759899689-dbnqgfo5srstp4eev2rj0pfc8j9b4kkm.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = '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'
########### FACEBOOK #######################
SOCIAL_AUTH_FACEBOOK_KEY = '985292215170699'
SOCIAL_AUTH_FACEBOOK_SECRET = '7b8483ff422109a7c17b3f7a03966bbf'
###########  TWITTER #######################
SOCIAL_AUTH_TWITTER_KEY = '9TD8f5fhasdsbf4w61GSM9' 
SOCIAL_AUTH_TWITTER_SECRET = 'mwtdcUe4uOvvjDk2Ausb45gsasdasdasashw65454TNSx'

